spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie
    username: kkh
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com #Gmail SMTP 서버주소
    port: 587 #STARTTLS 포트
    username: lobil7782@gmail.com # Gmail 주소
    password: mzwk dzxw tgng bixp # 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    spring3_4_5.boot: debug